### ISSUE TITLE
Can't use the relase and ca'nt compile

### ISSUE THREAD

**Issue by mrschaeffer2018** [CortexFoundation/PoolMiner#22]
I tried to use release but i get this error below i think is because i just could test with CUDA 9.0 and 10.2:

**************************************************************
**		Cortex GPU Miner			**
**************************************************************
0x0abf843a3459c0f493a098ce71d07d11d1b81931 cortex.us.woolypooly.com:40000
panic: plugin.Open("plugins/cuda_helper.so"): libcudart.so.9.2: cannot open shared object file: No such file or directory

goroutine 1 [running]:
github.com/CortexFoundation/PoolMiner/cortexminer.(*Cortex).Mining(0xc4200be100)
	/home/kaihuo/PoolMiner/build/_workspace/src/github.com/CortexFoundation/PoolMiner/cortexminer/miner.go:190 +0x57c
main.main()
	/home/kaihuo/PoolMiner/build/_workspace/src/github.com/CortexFoundation/PoolMiner/cmd/miner/main.go:73 +0x7bc

When i tried to compile on CUDA 10.2 on a 6.0 compute capability card i get this error:

nvcc -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52  -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70   -Xcompiler="-fPIC" -std=c++11 -O3 -c -o cudaN31L14.o.trimmer.o -rdc=true -DEDGEBITS=30 -DPROOFSIZE=42 -arch sm_35 -D_FORCE_INLINES src/cuda/trimmer.cu 
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1171): error: identifier "__builtin_ia32_reducess" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1179): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1189): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1198): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1207): error: identifier "__builtin_ia32_rangess128_round" is undefined

12 errors detected in the compilation of "/tmp/tmpxft_00000f38_00000000-12_trimmer.compute_70.cpp1.ii".
Makefile:36: recipe for target 'cudaN31L14.o.trimmer.o' failed
make[1]: *** [cudaN31L14.o.trimmer.o] Error 1
